version: "3.8"

services:
  neo4j:
    image: neo4j:4.4.20-community # Rolling back to a stable 4.x version
    hostname: neo4j
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt port
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins # Mount plugins directory
    environment:
      - NEO4J_AUTH=neo4j/password # Default username and password, change in production
      - NEO4J_dbms_memory_heap_initial__size=768M
      - NEO4J_dbms_memory_heap_max__size=768M
      - NEO4J_dbms_memory_pagecache__size=768M
      - NEO4J_SERVER_ACTIVATION_CODE= # Set if you have an Enterprise Edition license
      # Enable APOC and set allowed procedures
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.* # Allows all GDS and APOC procedures
